# Generated by Django 6.0.4 on 2026-04-22 11:21

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_homepage_advantage1_img_homepage_advantage1_text_and_more'),
        ('wagtailcore', '0096_referenceindex_referenceindex_source_object_and_more'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUsPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('body', wagtail.fields.StreamField([('rtfblock', 0), ('imgblock', 1)], blank=True, block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {'features': ['h1', 'h2', 'h3', 'ol', 'ul', 'hr', 'blockquote', 'superscript', 'subscript', 'strikethrough', 'bold', 'italic', 'link'], 'label': 'Текст'}), 1: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Изображение', 'template': 'blocks/image_block.html'})})),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='TourCategoryPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='advantage1_text',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='advantage1_title',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='advantage2_text',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='advantage2_title',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='advantage3_text',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='advantage3_title',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='advantage4_text',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='advantage4_title',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='hero_subtitle',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='hero_title',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.CreateModel(
            name='TourPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('price', models.CharField(blank=True, max_length=32, null=True)),
                ('short_desc', models.CharField(blank=True, max_length=255, null=True)),
                ('type', models.CharField(max_length=64)),
                ('guide', models.CharField(max_length=64)),
                ('duration', models.CharField(max_length=64)),
                ('date', models.CharField(max_length=64)),
                ('places', wagtail.fields.StreamField([('rtfblock', 0), ('imgblock', 1)], blank=True, block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {'features': ['h1', 'h2', 'h3', 'ol', 'ul', 'hr', 'blockquote', 'superscript', 'subscript', 'strikethrough', 'bold', 'italic', 'link'], 'label': 'Текст'}), 1: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Изображение', 'template': 'blocks/image_block.html'})})),
                ('desc', wagtail.fields.StreamField([('rtfblock', 0), ('imgblock', 1)], blank=True, block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {'features': ['h1', 'h2', 'h3', 'ol', 'ul', 'hr', 'blockquote', 'superscript', 'subscript', 'strikethrough', 'bold', 'italic', 'link'], 'label': 'Текст'}), 1: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Изображение', 'template': 'blocks/image_block.html'})})),
                ('include', wagtail.fields.StreamField([('rtfblock', 0), ('imgblock', 1)], blank=True, block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {'features': ['h1', 'h2', 'h3', 'ol', 'ul', 'hr', 'blockquote', 'superscript', 'subscript', 'strikethrough', 'bold', 'italic', 'link'], 'label': 'Текст'}), 1: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Изображение', 'template': 'blocks/image_block.html'})})),
                ('photos', wagtail.fields.StreamField([('imgblock', 0)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Изображение', 'template': 'blocks/image_block.html'})})),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
