# Generated by Django 6.0.4 on 2026-04-30 18:13

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_aboutuspage_tourcategorypage_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tourpage',
            name='date',
        ),
        migrations.RemoveField(
            model_name='tourpage',
            name='desc',
        ),
        migrations.RemoveField(
            model_name='tourpage',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='tourpage',
            name='guide',
        ),
        migrations.RemoveField(
            model_name='tourpage',
            name='include',
        ),
        migrations.RemoveField(
            model_name='tourpage',
            name='places',
        ),
        migrations.RemoveField(
            model_name='tourpage',
            name='type',
        ),
        migrations.AddField(
            model_name='homepage',
            name='istagram_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='telegram_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='whatsapp_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tourpage',
            name='max_people',
            field=models.IntegerField(blank=True, null=True, verbose_name='Макс. кол-во человек'),
        ),
        migrations.AddField(
            model_name='tourpage',
            name='price_delta',
            field=models.IntegerField(blank=True, null=True, verbose_name='Дельта цены для умножения на количество человек'),
        ),
        migrations.AddField(
            model_name='tourpage',
            name='text',
            field=wagtail.fields.StreamField([('rtfblock', 0), ('imgblock', 1)], blank=True, block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {'features': ['h1', 'h2', 'h3', 'ol', 'ul', 'hr', 'blockquote', 'superscript', 'subscript', 'strikethrough', 'bold', 'italic', 'link'], 'label': 'Текст'}), 1: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Изображение', 'template': 'blocks/image_block.html'})}, null=True, verbose_name='Описание тура'),
        ),
        migrations.AlterField(
            model_name='tourpage',
            name='photos',
            field=wagtail.fields.StreamField([('imgblock', 0)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Изображение', 'template': 'blocks/image_block.html'})}, null=True),
        ),
        migrations.AlterField(
            model_name='tourpage',
            name='price',
            field=models.IntegerField(blank=True, null=True, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='tourpage',
            name='short_desc',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Краткое описание'),
        ),
    ]
