# Generated by Django 6.0.4 on 2026-05-19 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_remove_tourpage_date_remove_tourpage_desc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='photo_text',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Текст над фото'),
        ),
    ]
