# Generated by Django 6.0.4 on 2026-08-06 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_presentationpage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tourpage',
            name='max_people',
        ),
        migrations.RemoveField(
            model_name='tourpage',
            name='price_delta',
        ),
    ]
