# Generated by Django 6.0.4 on 2026-08-06 19:06

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_remove_tourpage_max_people_and_more'),
        ('wagtailcore', '0096_referenceindex_referenceindex_source_object_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_agreement',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('text', wagtail.fields.StreamField([('rtfblock', 0), ('imgblock', 1)], blank=True, block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {'features': ['h1', 'h2', 'h3', 'ol', 'ul', 'hr', 'blockquote', 'superscript', 'subscript', 'strikethrough', 'bold', 'italic', 'link'], 'label': 'Текст'}), 1: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Изображение', 'template': 'blocks/image_block.html'})}, null=True, verbose_name='Текст пользовательского соглашения')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
