# Generated by Django 6.0.4 on 2026-08-06 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_user_agreement'),
        ('wagtailcore', '0096_referenceindex_referenceindex_source_object_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='user_agreement',
            new_name='UserAgreement',
        ),
    ]
