# Generated by Django 6.0.4 on 2026-08-08 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_rename_user_agreement_useragreement'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Адрес'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='co_founder_mail',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Почта сооснователя'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='founder_mail',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Почта основателя'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='nib',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Третий блок'),
        ),
    ]
